### ISSUE TITLE
[BUG] Status 500 when trying to search user

### ISSUE THREAD

**Issue by DillonB07** [JBYT27/GitHub-User-Search#8]
![Screen Recording 2021-11-10 at 7 24 04 pm](https://user-images.githubusercontent.com/83948303/141179611-875bb806-c04c-4840-a3f8-5ab92c4a14f0.gif)

*This happens quite often. Though not 100% of the time*

**Comment by JBYT27** [comment]
Hmm, idk, it works on my side always, but idk. Let me try later on (I have already tried it rn)

**Comment by DillonB07** [comment]
Maybe just add the 500 catch back in and leave it at that. Seems to work most times. Maybe it was just yesterday as it's working fine today.

**Comment by JBYT27** [comment]
Oh, okay, sure thing!
